---

- name: Gather facts and create table
  hosts: poc_ios
  gather_facts: no

  tasks:
    - name: Get facts info from device
      ios_facts:
        gather_subset:
          - hardware

    - name: Debug hostvars
      debug: var=hostvars
